# """mysite URL Configuration
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/1.10/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.conf.urls import url, include
#     2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
# """
# from django.conf.urls import url, include
# from django.contrib import admin
#
# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     url(r'', include('entity.urls')),
# ]

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

from rest_framework import routers
from entity.views import *

# We use a single global DRF Router that routes views from all apps in project
router = routers.DefaultRouter()

# app views and viewsets
router.register(r'appointment', ApppointmentViewSet, r"appointment")
# router.register(r'appointment/patient',PatientAppointmentsList,r"appointment/patient")
router.register(r'patient', PatientViewSet, r"patient")

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),

    # root view of our REST api, generated by Django REST Framework's router
    url(r'^api/', include(router.urls, namespace='api')),

    url(r'^api/patient/(?P<patient>[^/.]+)/appointments/$',PatientAppointmentsList.as_view()),

    # index page should be served by django to set cookies, headers etc.
    url(r'^$', index_view,{}, name='index_view'),

    url(r'^patient/$', patient_list, name='patient_list'),
    url(r'^appointment/$', appointment_list, name='appointment_list'),
    url(r'^appointmentlist/(?P<pk>\w+)/$', patient_appointment_list, name='patient_appointment_list'),
    url(r'^patient/new/$', patient_edit, name='patient_edit'),
    url(r'^appointment/new/$', appointment_edit, name='appointment_edit'),
    # url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

# let django built-in server serve static and media content
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
