# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth',
            field=models.DateField(),
        ),
    ]
